### ISSUE TITLE
删除CODE_OF_CONDUCT.md中部分与其它文件重复内容

### ISSUE THREAD

**Issue by tyvekzhang** [tyvekzhang/fastapi-sqlmodel-starter#107]
### What would you like to be added?

删除CODE_OF_CONDUCT.md中部分与其它文件重复内容

### Requirement reference?

1. 文件地址: https://github.com/tyvekzhang/fastapi-sqlmodel-starter/blob/main/.github/CODE_OF_CONDUCT.md
2. 删除内容位置为图中标记:
![image](https://github.com/tyvekzhang/fastapi-sqlmodel-starter/assets/133777454/696c3196-0ca3-4342-952c-e0ae4c0751ee)

### Acceptance Criteria

<details>
1. 标记位置删除
2. CI通过
</details>

**Comment by xuqiu-qiu** [comment]
123
