### ISSUE TITLE
删除.github中不必要的模板文件-flaking-test.yaml

### ISSUE THREAD

**Issue by tyvekzhang** [tyvekzhang/fastapi-sqlmodel-starter#109]
### What would you like to be added?

删除.github中不必要的模板文件-flaking-test.yaml

### Requirement reference?

1. 文件地址: https://github.com/tyvekzhang/fastapi-sqlmodel-starter/tree/main/.github
2. 文件名称: failing-test.yaml

### Acceptance Criteria

<details>
1. 文件删除
 2. CI通过
</details>

**Comment by xuqiu-qiu** [comment]
11
