### ISSUE TITLE
添加github的workflows配置

### ISSUE THREAD

**Issue by tyvekzhang** [tyvekzhang/fastapi-sqlmodel-starter#46]
### What would you like to be added(你想添加什么功能)?

代码合并前做检查, 校验

### Requirement reference(功能、界面参考的文档或链接)?

https://github.com/flutter/flutter/tree/master/.github/workflows
https://github.com/freeCodeCamp/freeCodeCamp/tree/main/.github/workflows
https://github.com/microsoft/TypeScript/tree/main/.github/workflows

### Acceptance Criteria(验收标准)

项目构建：你可以设置在每次提交或者在特定条件下自动运行编译和构建代码。
自动测试：在每次提交代码、创建或更新 Pull Request 的时候自动运行测试，保证代码的质量。
自动部署：当代码推送到特定分支或者新的 Release 生成时，自动将代码部署到预设的环境中。
代码格式检查：在创建或更新 Pull Request 的时候自动运行例如 ESLint, Prettier 等工具对代码格式进行检查。
自动生成文档：当代码更新时，自动更新对应的 API 文档。
发布管理：使用 GitHub Workflow 可以自动将项目软件发布到 GitHub Releases，或者发布到 npm, docker hub等平台。
异常通知：在工作流程运行出错的时候，通过邮件或其他方式警告相关人员。
标签管理：当 Pull Request 通过或者 Issue 关闭时，可以自动添加或删除对应的标签。

**Comment by zhangjunyangz** [comment]
我来试一下, 可以吗
